### PR TITLE
Add composer version

### PR DESCRIPTION
**Pull request by afbora**
For 3.8 compatibility

### CODE REVIEW

**Comment by renestalder** [comment]
I thought this is discouraged? 

Based on https://getcomposer.org/doc/04-schema.md#version

> Optional if the package repository can infer the version from somewhere, such as the VCS tag name in the VCS repository. In that case it is also recommended to omit it.

> Note: Packagist uses VCS repositories, so the statement above is very much true for Packagist as well. Specifying the version yourself will most likely end up creating problems at some point due to human error.

**Comment by afbora** [comment]
This is not a mandatory change, but is necessary so that it always displays the correct version no matter how the install to Kirby app.

You can check out following comments of mine and @lukasbestle https://github.com/getkirby/kirby/issues/4733#issuecomment-1264489117

**Comment by renestalder** [comment]
Ah, cool. Good to know. Thanks for the information. :)

**Comment by lukasbestle** [comment]
The migration guide for 3.8 will include this section with an explanation:

https://github.com/getkirby/getkirby.com/blob/01493db29551777cb1c9992cecb01054b68d5a7c/content/releases/3-8/2_migration-plugins/release-guide.txt#L42-L46

**Pull request closed without merging**
